// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsBNEdnHWtQ5KrMe7Tp7LeLVFMBLlANno',
    appId: '1:907521806982:web:70b43c793ad07cad87f707',
    messagingSenderId: '907521806982',
    projectId: 'flutter-animation-9cf43',
    authDomain: 'flutter-animation-9cf43.firebaseapp.com',
    databaseURL: 'https://flutter-animation-9cf43-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-animation-9cf43.appspot.com',
    measurementId: 'G-4Z32T2NCW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe0GWuPSmyf9HkRDiW8Ng8sTIhFZ7Iimo',
    appId: '1:907521806982:android:985d2d7b9ed3224a87f707',
    messagingSenderId: '907521806982',
    projectId: 'flutter-animation-9cf43',
    databaseURL: 'https://flutter-animation-9cf43-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-animation-9cf43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDurdWK0lLWpUxf3uQ61_dhNzc9gDEW0uk',
    appId: '1:907521806982:ios:7910e54effc97fbc87f707',
    messagingSenderId: '907521806982',
    projectId: 'flutter-animation-9cf43',
    databaseURL: 'https://flutter-animation-9cf43-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-animation-9cf43.appspot.com',
    iosBundleId: 'com.example.flutterAnimation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDurdWK0lLWpUxf3uQ61_dhNzc9gDEW0uk',
    appId: '1:907521806982:ios:7910e54effc97fbc87f707',
    messagingSenderId: '907521806982',
    projectId: 'flutter-animation-9cf43',
    databaseURL: 'https://flutter-animation-9cf43-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-animation-9cf43.appspot.com',
    iosBundleId: 'com.example.flutterAnimation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsBNEdnHWtQ5KrMe7Tp7LeLVFMBLlANno',
    appId: '1:907521806982:web:11bc9d127d86e95087f707',
    messagingSenderId: '907521806982',
    projectId: 'flutter-animation-9cf43',
    authDomain: 'flutter-animation-9cf43.firebaseapp.com',
    databaseURL: 'https://flutter-animation-9cf43-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-animation-9cf43.appspot.com',
    measurementId: 'G-PQSPC3GR12',
  );
}
